config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  devise_for :users
  get "properties/search", to: "properties#search", as: :search_properties
  get "properties/reports", to: "properties#reports", as: :property_reports
  put "properties/:id/purchase", to: "properties#purchase", as: :purchase_property
  resources :properties

  root to: "properties#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :properties, only: :index
      resources :sessions, only: [:create, :destroy]
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      cannot :purchase, Property
      can :manage, :all
    elsif user.agent?
      can :read, Property
      can :manage, Property, owner_id: user.id
      cannot :reports, Property
      can :manage, Address, property: { id: user.property_ids }
      can :purchase, Property, id: User.where.not(id: user.id).map(&:property_ids).flatten
    elsif user.customer?
      can :read, Property
      can :manage, Property, owner_id: user.id
      cannot :reports, Property
      can :manage, Address, property: { id: user.property_ids }
      can :purchase, Property, id: User.where.not(id: user.id).map(&:property_ids).flatten
    else
      can :read, Property
      cannot :reports, Property
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base

  validates :building, :street, :city, :state, :country, :zip, presence: true

  belongs_to :property

  before_save :titleize_attributes

  geocoded_by :street_address
  after_validation :geocode

  def street_address
    [street, city, state, country].compact.join(', ')
  end

  private

    def titleize_attributes
      self.city = city.titleize
      self.state = state.titleize
      self.country = country.titleize
    end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :property
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment :image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
end

app/models/property.rb
class Property < ActiveRecord::Base
  enum available_for: [:rent, :sale]

  validates :description, :available_for, :owner_id, presence: true

  has_one :address, dependent: :destroy
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  has_many :pictures, dependent: :destroy
  belongs_to :customer, class_name: "User", foreign_key: "customer_id"

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :pictures, :allow_destroy => true

  scope :by_country, ->(country) { joins(:address).where("addresses.country like ?", "%#{country}%")}
  scope :by_type_and_availability, ->(type, availability) { includes(:address, :owner, :customer).where(available: availability, available_for: Property.available_fors[type]) }
  scope :sold_in_year, -> (year) { where( "YEAR(sold_or_rented_on) = ?", year ) }
end

app/models/report_pdf.rb
class ReportPdf < Prawn::Document
  def initialize(properties)
    super()
    @properties = properties
    table_content
  end

  def table_content
    table property_rows do
      row(0).font_style = :bold
      self.header = true
      self.row_colors = ['DDDDDD', 'FFFFFF']
      self.column_widths = [40, 200, 100, 100, 100]
    end
  end

  def property_rows
    [["#", "Description", "Address", "Owner", "Customer"]] +
      @properties.map do |property|
      [property.id, property.description, property.address.street_address, property.owner.name, property.try(:customer).try(:name)]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :mobile_number, :role, presence: true
  validates :mobile_number, uniqueness: true
  validates_inclusion_of :role, :in => %w( admin agent customer guest )

  has_many :properties, foreign_key: "owner_id", dependent: :destroy
  has_many :purchased_properties, class_name: "Property", foreign_key: "customer_id", dependent: :destroy

  enum role: [:admin, :agent, :customer]

  before_create :generate_authentication_token!

  private

    def generate_authentication_token!
      begin
        self.auth_token = Devise.friendly_token
      end while self.class.exists?(auth_token: auth_token)
    end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  include Authenticable
end

app/controllers/api/v1/properties_controller.rb
class Api::V1::PropertiesController < Api::V1::ApplicationController
  before_action :authenticate_with_token!
  respond_to :json

  def index
    respond_with Property.all
  end
end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Api::V1::ApplicationController

  def create
    user_password = params[:session][:password]
    user_email = params[:session][:email]
    user = user_email.present? && User.find_by(email: user_email)

    if user.valid_password? user_password
      sign_in user, store: false
      user.generate_authentication_token!
      user.save
      render json: user, status: 200, location: [:api, user]
    else
      render json: { errors: "Invalid email or password" }, status: 422
    end
  end

  def destroy
    user = User.find_by(auth_token: params[:id])
    user.generate_authentication_token!
    user.save
    head 204
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/concerns/authenticable.rb
module Authenticable

  # Devise methods overwrites
  def current_user
    @current_user ||= User.find_by(auth_token: request.headers['Authorization'])
  end

  def authenticate_with_token!
    render json: { errors: "Not authenticated" },
                status: :unauthorized unless user_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show, :search]
  before_action :load_countries, only: [:index, :search]
  load_resource :property
  load_resource :address, through: :property

  def new
    @property.build_address
  end

  def create
    @property = current_user.properties.build(property_params)
    if @property.save
      redirect_to properties_path, flash: { success: "Property details saved successfully." }
    else
      render "new"
    end
  end

  def update
    @property = Property.find_by(id: params[:id])
    if @property.update_attributes(property_params)
      redirect_to properties_path, flash: { success: "Property details updated successfully." }
    else
      render "edit"
    end
  end

  def search
    @properties = Property.by_country(params[:country])
    render "index"
  end

  def reports
    @type = params[:type]
    reporting_service = ReportingService.new(@type)
    @properties = reporting_service.find_properties_data
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ReportPdf.new(@properties)
        send_data pdf.render, filename: "report_#{params[:type]}.pdf", type: "application/pdf"
      end
    end
  end

  def purchase
    if @property.update_attributes(customer_id: current_user.id, sold_or_rented_on: Date.today, available: false)
      redirect_to properties_path, flash: {success: "Property updated successfully."}
    else
      render "show", flash: {error: @property.errors.full_messages.join("\n")}
    end
  end

  private

    def property_params
      params.require(:property).permit(:description, :established_on, :available_for, address_attributes: [:building, :street, :landmark, :city, :state, :country, :zip], pictures_attributes: [:image])
    end

    def load_countries
      @countries = Address.pluck(:country).uniq
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Real State</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "shared/header" %>
<%= render partial: "shared/flash_messages" %>
<%= yield %>

</body>
</html>

app/views/properties/_address_fields.html.erb
<%= f.fields_for :address, property.address do |faddr| %>
  <div class="property-row">
    <label>Building<span class="required">*</span>: </label>
    <%= faddr.text_field :building %>
  </div>
  <div class="property-row">
    <label>Street<span class="required">*</span>: </label>
    <%= faddr.text_field :street %>
  </div>
  <div class="property-row">
    <label>Landmark: </label>
    <%= faddr.text_field :landmark %>
  </div>
  <div class="property-row">
    <label>City<span class="required">*</span>: </label>
    <%= faddr.text_field :city %>
  </div>
  <div class="property-row">
    <label>State<span class="required">*</span>: </label>
    <%= faddr.text_field :state %>
  </div>
  <div class="property-row">
    <label>Country<span class="required">*</span>: </label>
    <%= faddr.text_field :country %>
  </div>
  <div class="property-row">
    <label>Zip Code<span class="required">*</span>: </label>
    <%= faddr.text_field :zip %>
  </div>
<% end %>

app/views/properties/_form.html.erb
<%= form_for property, url: {action: action}, html: { multipart: true } do |f| %>
  <%= render partial: "address_fields", locals: {f: f, property: property} %>
  <div class="property-row">
    <label>Description<span class="required">*</span>: </label>
    <%= f.text_field :description %>
  </div>
  <div class="property-row">
    <label>Established On: </label>
    <%= f.date_select :established_on, { include_blank: true } %>
  </div>
  <div class="property-row">
    <label>Available for<span class="required">*</span>: </label>
    <% Property.available_fors.each do |key, value| %>
      <%= f.radio_button :available_for, key %><%= key.titleize %>
    <% end %>
  </div>
  <%= render partial: "pictures", locals: {f: f, property: property} %>
  <div class="property-row">
    <%= f.submit "Save Property" %>
    <%= link_to "Cancel", properties_path %>
  </div>
<% end %>

app/views/properties/_pictures.html.erb
<div class="property-row">
  <label>Pictures: </label>
  <%= file_field_tag("property_pictures_image", multiple: true, name: "property[pictures_attributes][][image]") %>
  <% if property.pictures.any? %>
    <% property.pictures.each do |pic| %>
      <%= image_tag pic.image.url(:thumb) %>
    <% end %>
  <% end %>
</div>

app/views/properties/_properties.html.erb
<% properties.each do |p| %>
  <div class="property-info">
    <% if can? :update, p %>
      <%= link_to edit_property_path(p) do %>
        <%= p.description %>
        <%= image_tag p.pictures.first.image.url(:thumb) if p.pictures.any? %>
      <% end %>
    <% else %>
      <%= link_to property_path(p) do %>
        <%= p.description %>
        <%= image_tag p.pictures.first.image.url(:thumb) if p.pictures.any? %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/properties/_properties_search.html.erb
<br />
<%= form_tag search_properties_url, method: :get do %>
  <%= select_tag "country", options_for_select(@countries) %>
  <%= submit_tag "Search" %>
<% end %>
<br />

app/views/properties/_property_links.html.erb
<div class="float-right">
  <% if can? :create, Property %>
    <%= link_to "Add New Property", new_property_path %><br />
  <% end %>
</div>

app/views/properties/_reports_links.html.erb
  <% if can? :reports, Property %>
    <h2>Reports</h2>
    <%= link_to "Properties available for rent", property_reports_path(type: "rent") %><br />
    <%= link_to "Properties available for sale", property_reports_path(type: "sale") %><br />
    <%= link_to "Properties sold this year", property_reports_path(type: "sold") %><br />
    <%= link_to "Properties rented this year", property_reports_path(type: "rented") %><br />
  <% end %>

app/views/properties/edit.erb
<h1><%= t('edit_property_title') %></h1>
<%= render partial: "shared/errors", locals: { object: @property } %>
<%= render partial: "form", locals: { property: @property, action: "update" } %>

app/views/properties/edit.html.erb
<h1><%= t('edit_property_title') %></h1>
<%= render partial: "shared/errors", locals: { object: @property } %>
<%= render partial: "form", locals: { property: @property, action: "update" } %>

app/views/properties/index.html.erb
<%= render partial: "property_links" %>
<%= render partial: "reports_links" %>
<%= render partial: "properties_search" %>
<%= render partial: "properties", locals: { properties: @properties } %>

app/views/properties/new.html.erb
<h1><%= t('new_property_title') %></h1>
<%= render partial: "shared/errors", locals: { object: @property } %>
<%= render partial: "form", locals: { property: @property, action: "create" } %>

app/views/properties/reports.html.erb
<% if @properties.any? %>
  <%= link_to "Export to PDF", property_reports_path(type: @type, format: "pdf") %>
  <%= render partial: "properties", locals: { properties: @properties } %>
<% else %>
  <%= t('no_property_message') %>
<% end %>
<%= link_to "Back to properties", properties_path, class: "float-right" %>

app/views/properties/show.html.erb
<script src="http://maps.googleapis.com/maps/api/js?key=####################&sensor=false" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<%= link_to "Back to properties", properties_path, class: "float-right" %>
<% if @property.available? && can?(:purchase, @property) %>
  <%= link_to "Purchase", purchase_property_path(@property), method: :put %>
<% end %>
<h2><%= @property.description %></h2>
<b>Established On:</b> <%= @property.established_on || "Not provided" %><br/>
<% if @property.available? %>
  <b>Available For:</b> <%= @property.available_for.titleize %><br />
<% else %>
  <b>Not available since:</b> <%= @property.sold_or_rented_on %><br />
<% end %>
<b>Address:</b> <%= @property.address.building +  ", " %><%= @property.address.street +  ", " %>
<%= "#{@property.address.landmark}, " if @property.address.landmark.present?  %>
<%= @property.address.city.titleize +  ", " %>
<%= @property.address.state.titleize +  ", " %>
<%= @property.address.country.titleize +  ", " %>
<%= @property.address.zip %><br />
<% if @property.pictures.any? %>
  <b>Images:</b><br />
  <% @property.pictures.each do |pic| %>
    <%= image_tag pic.image.url(:medium) %>
  <% end %>
<% end %><br />
<b>Map:</b>
<div style='width: 800px;'>
  <div id="one_marker" style='width: 800px; height: 400px;'></div>
</div>
<script>
  $(document).ready(function() {
    buildMap(<%= @property.address.latitude.to_s %>, <%= @property.address.longitude.to_s %>);
  });
</script>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this mark from being saved:</h2>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <br />
<% end %>

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "flash #{key}" %>
  <% end %>
  <br />
<% end %>

app/views/shared/_header.html.erb
<div class="float-right">
  <% if current_user %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Login", new_user_session_path %>
    <% if can? :create, User %>
      | <%= link_to "Register", new_user_registration_path %>
    <% end %>
  <% end %>
</div>
<h1>Real State</h1>